#!/usr/bin/env python3
"""Self-host the Inter font from Google Fonts (SIL Open Font License 1.1).

The site currently loads Inter from fonts.googleapis.com / fonts.gstatic.com.
This script removes that dependency: it downloads the Google Fonts CSS for
Inter (weights 400/500/600/700/800) and the woff2 files, keeps only the
`latin` + `latin-ext` subsets (all site text is EN/DE; the latin subset covers
ä ö ü ß), and writes:

    site/fonts.css          @font-face rules with relative urls
    site/fonts/*.woff2      the font files (unmodified, OFL-licensed)
    site/fonts/OFL.txt      the SIL Open Font License text

index.html then links `fonts.css` from the same origin — no external font
host, nothing to stall first paint, nothing to block on a third-party domain.

Re-run after changing the weight list. Requires outbound HTTPS.
"""
import hashlib
import os
import re
import urllib.request

ROOT = os.path.dirname(os.path.abspath(__file__))
FONT_DIR = os.path.join(ROOT, "site", "fonts")
CSS_PATH = os.path.join(ROOT, "site", "fonts.css")
OFL_URL = "https://raw.githubusercontent.com/google/fonts/main/ofl/inter/OFL.txt"

WEIGHTS = "400;500;600;700;800"
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36")
KEEP_SUBSETS = {"latin", "latin-ext"}


def fetch(url, binary=False):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        return r.read() if binary else r.read().decode("utf-8")


def main():
    css_url = (f"https://fonts.googleapis.com/css2"
               f"?family=Inter:wght@{WEIGHTS}&display=swap")
    print(f"fetching {css_url}")
    css = fetch(css_url)

    # Google's CSS is one /* subset */ comment followed by one @font-face block.
    blocks = re.findall(r"/\*\s*([a-z-]+)\s*\*/\s*(@font-face\s*\{[^}]*\})", css)
    print(f"found {len(blocks)} subset blocks")

    os.makedirs(FONT_DIR, exist_ok=True)
    out = []
    written = {}  # (subset, content-hash) -> first weight that used this file
    for subset, block in blocks:
        if subset not in KEEP_SUBSETS:
            continue
        weight = re.search(r"font-weight:\s*(\d+)", block).group(1)
        url = re.search(r"url\((\S+?)\)", block).group(1)
        data = fetch(url, binary=True)
        # Google serves the VARIABLE font for every requested weight (all
        # weights return identical bytes), so dedupe by content: one file per
        # subset, referenced by every weight rule.
        key = (subset, hashlib.md5(data).hexdigest())
        if key not in written:
            fname = f"inter-{weight}-{subset}.woff2"
            with open(os.path.join(FONT_DIR, fname), "wb") as f:
                f.write(data)
            written[key] = fname
            print(f"  {subset:10} -> fonts/{fname} ({len(data)/1024:.0f} KB)")
        else:
            fname = written[key]
        out.append(block.replace(url, f"fonts/{fname}"))

    # Drop stale files (e.g. after a weight-list change or subset change).
    keep = {os.path.basename(m) for m in re.findall(r"url\(fonts/([^)]+)\)", "\n".join(out))}
    for f in os.listdir(FONT_DIR):
        if f.endswith(".woff2") and f not in keep:
            os.remove(os.path.join(FONT_DIR, f))
            print(f"  removed stale {f}")

    header = (
        "/* Inter font family — self-hosted from Google Fonts.\n"
        "   License: SIL Open Font License 1.1 (see fonts/OFL.txt).\n"
        "   Generated by selfhost_fonts.py · subsets: latin, latin-ext "
        "(site text is EN/DE). */\n"
    )
    with open(CSS_PATH, "w", encoding="utf-8") as f:
        f.write(header + "\n".join(out) + "\n")

    try:
        ofl = fetch(OFL_URL)
        with open(os.path.join(FONT_DIR, "OFL.txt"), "w", encoding="utf-8") as f:
            f.write(ofl)
        print(f"  wrote fonts/OFL.txt")
    except Exception as e:  # noqa: BLE001 - license text is a nice-to-have
        print(f"  WARNING: could not fetch OFL.txt: {e}")

    print(f"wrote {CSS_PATH} with {len(out)} @font-face rules")


if __name__ == "__main__":
    main()
